### ISSUE TITLE
It goes too high

### ISSUE THREAD

**Issue by enrigisbert** [wgcv/RewriteM600#2]
When it's turn of the color change it goes +80mm in relative distance, that's not an issue on low prints, but in prints that approaches to the machine limits i think it could be a problem.
It would be great if there was a tab to change the parameters of the color change

**Comment by wgcv** [comment]
It is going to up until the z size can up after the marlin is going to ignore, but it is a good idea!! 
Please check and test.
Install in Octoprint the feature: https://github.com/wgcv/RewriteM600/archive/Add-zdistance.zip
The branch: https://github.com/wgcv/RewriteM600/tree/Add-zdistance
